### ISSUE TITLE
CLI project not parsed

### ISSUE THREAD

**Issue by altschuler** [mgechev/ngrev#20] opened 2017-06-27 09:09 UTC
I'm trying to parse a CLI project, but end up with this screen https://i.imgur.com/mKq5YYM.png

I see the modules being listed in the output, so it's finding something. Last few lines of output is this:

```
AppModule
Project loaded
Getting data
Get symbols
Get symbols
```

Very exciting project :)

**Comment by mgechev** [comment] 2017-06-27 09:40
I see only part of the screen on this screenshot. Would you share the entire window?

**Comment by altschuler** [comment] 2017-06-27 09:44
Sorry, should have clarified. That's the entire content of the window, rest is just white. Clicking the green box does nothing.

**Comment by mgechev** [comment] 2017-06-27 10:37
If you can share source code so I can try debugging the project it'll great.

**Comment by altschuler** [comment] 2017-06-27 11:22
Sorry I can't really do that. I can answer any question or clarify/elaborate on architecture, but I can't send you all the code :/

**Comment by mgechev** [comment] 2017-06-27 11:35
Yes, sharing proprietary code won't be a good idea :-).

The architecture does not matter for the source code visualization. It'll be helpful if you can provide a sample project that I can test the tool against. Doesn't have to be your original project.

**Comment by altschuler** [comment] 2017-06-27 12:18
Roger, I'll try to make something reproducible I can share with you. Thank you very much for the quick response and effort! :-)

**Comment by mgechev** [comment] 2017-06-27 12:40
Thanks, this will be helpful!

**Comment by altschuler** [comment] 2017-09-14 15:08
I never got any further with this, but realized that I've got quite a few circular dependencies. Might that be the issue?

**Comment by mgechev** [comment] 2017-09-14 17:45
I'm handling circular dependencies to some extent but it's possible.

**Comment by bobKasbi** [comment] 2017-11-13 16:38
Any news about this issue? I'am facing the same. Thanks!

**Comment by altschuler** [comment] 2017-11-13 17:10
@bobKasbi do you have any circular dependencies in your project? The CLI will warn against it if you didn't explicitly disable it.

**Comment by bobKasbi** [comment] 2017-11-14 10:23
@altschuler: no, I don't.

**Comment by HermenOtter** [comment] 2017-11-21 10:56
@mgechev I see the same screen as @altschuler. I cannot share my code as well. Do you support Angular 4?

**Comment by mgechev** [comment] 2017-12-21 21:43
Yes, Angular version 4 is supported by version 0.0.11. Angular v5 is supported by 0.0.13.

Closing the issue because of lack of details which will help me reproduce it.

**Closed by mgechev** 2017-12-21 21:43 UTC
